#!/usr/bin/bash
# Command line convert milliseconds to a string timestamp
if [[ -z "$1" ]]; then
  printf 'Millisecond timestamp required.\n'
  exit 1
fi

perl -e "print scalar localtime($1 / 1000)"
echo
