#!/usr/bin/bash
# modified from http://ix.io/3EVc
# Read .env file for whatever program you are using it for.
# Usage 
#   $1 - key_name -- ie. STREAMKEY
#   $2 file to read from
read_env_var() {
    VAR=$(grep --color=never "$1" "$2")
    echo "${VAR#*=}"
}


read_env_var "$@"
