#!/bin/bash

# Gotta delete then re-add. Whatever, CentOS.
sudo ip tuntap del dev tap0 mode tap
sudo ip tuntap add dev tap0 mode tap
sudo ip link set tap0 up promisc on
sudo ip link set dev virbr0 up  # as needed
sudo ip link set dev tap0 master virbr0
