#!/bin/bash
# Helper script for setting up a kvm-based VM
# This is used to find IOMMU groups to pass through to the VM 
# (mainly used for OSX/iPhone-forwarding)

for g in /sys/kernel/iommu_groups/*; do
    echo "IOMMU Group ${g##*/}:"
    for d in $g/devices/*; do
        echo -e "\t$(lspci -nns ${d##*/})"
    done;
done;
