#!/bin/bash
# Helper script for setting up a kvm-based VM
# This is used to list USB controllers and IOMMU Groups 
# Mainly used for OSX/iPhone-forwarding over USB by blacklisting 
# the port it is connected to on my hub.

for usb_ctrl in $(find /sys/bus/usb/devices/usb* -maxdepth 0 -type l)
do 
	pci_path="$(dirname "$(realpath "${usb_ctrl}")")"
	echo "Bus $(cat "${usb_ctrl}/busnum") --> $(basename $pci_path)
	(IOMMU group $(basename $(realpath $pci_path/iommu_group)))"
	lsusb -s "$(cat "${usb_ctrl}/busnum"):"
	echo
done

