#!/usr/bin/bash
# download to mp3 or vorbis
# using mpv + yt-dlp

readonly YT="$1"
format="${2:-mp3}"
format="${format,,}"

if [[ -z $YT ]]; then
  printf "Error: youtube URL required\n"
  exit 1
fi

if [[ $YT != *youtube.com/* && $YT != *soundcloud.com/* && $YT != *youtu.be/* ]]; then
  printf "Error: only youtube.com URLs are supported\n"
  exit 1
fi

if [[ ! $format =~ mp3|vorbis|ogg ]]; then
  printf "Error: only mp3 and ogg(vorbis) allowed"
fi

if [[ $format == "ogg" ]]; then # correct to vorbis
  format="vorbis"
fi

if [[ $format == "mp3" ]]; then
  format_flags="-t mp3"
else
  format_flags="-x --audio-format $format"
fi

filename_template='%(uploader)s - %(title)s.%(ext)s'
if [[ $YT == *soundcloud.com/* ]]; then
  filename_template='%(artist)s - %(title)s.%(ext)s'
fi

yt-dlp -o "$filename_template" $format_flags --embed-metadata --no-mtime "$YT"
